server:
  port: 8081

spring:
  application:
    name: auth-service
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

app:
  init:
    enabled: false
    admin:
      email: ${ADMIN_EMAIL}
      password: ${ADMIN_PASSWORD}
  security:
    authenticated-endpoints:
      "/auth/logout"
    public-endpoints:
      "/auth/**, 
      /users/register, 
      /users/activate,
      /users/resend-activation"
    cors-allowed-origins: "http://localhost:3000"
    jwt:
      access-token-secret-key: ${JWT_ACCESS_SECRET_KEY}
      refresh-token-secret-key: ${JWT_REFRESH_SECRET_KEY}
      access-token-expiration: 3600000 # 1 hour
      refresh-token-expiration: 604800000 # 7 days
#      access-token-expiration: 15000 #milisecond ~ 15s
#      refresh-token-expiration: 60000 #~1 minute
      access-token-cookie-name: accessToken
      refresh-token-cookie-name: refreshToken
